version: '3.7'

services:
  dev_vue:
    tty: true
    container_name: dev_vue
    build:
      context: ./vue
      dockerfile: DockerFile
    command: npm run dev
    volumes:
      - '../vue:/vue'
    ports:
      - 420:420
    networks:
      - npmnetwork
  dev_laravel:
    build:
      context: ./laravel
      dockerfile: DockerFile
    container_name: dev_laravel
    command: php artisan serve --host=0.0.0.0
    ports:
    - 4200:4200
    tty: true
    working_dir: /var/www
    volumes:
        - ../laravel:/var/www
    networks:
      - npmnetwork
  dev_mysql:
    image: mysql
    restart: always
    container_name: dev_mysql
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test123
    networks:
      - npmnetwork
networks:
    npmnetwork:
        external: true
        driver: bridge
volumes:
  database:
    driver: local